### ISSUE TITLE
assert does not normally work

### ISSUE THREAD

**Issue by about-midnight** [tehmou/rx-android-architecture#66]
assert statements [do not normally work](http://stackoverflow.com/a/5563637/1543076). 
```java
assert false; // code has no effect
```
see https://github.com/tehmou/rx-android-architecture/blob/feature/database-routes/app/src/main/java/com/tehmou/rxbookapp/data/base/provider/ContractContentProviderBase.java#L23

**Comment by jaggernod** [comment]
I agree, we probably need to have our own preconditions. Don't want to add Guava dependency

**Comment by jaggernod** [comment]
Thanks for the comment. Started using Preconditions from: rx.android.internal
